### ISSUE TITLE
Aurelia-Polymer1-TypeScript-Electron?

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [pyarmak/aurelia-electron-starter#5]
Hi,

Thank you for Aurelia-MateriazlieCSS-TypeScript-Electron.

I thought it should be my scaffold. But after looking at Polymer 1.0, I think I should use Aurelia-TypeScript -Polymer 1.0?? I’m afraid of much trouble with Polymer.

How do you think about Polymer 1.0? It has much more components than materializeCSS.

I wish someone provides a skeleton of Aurelia-Polymer1-TypeScript-Electron.

This one is a DB example with Aurelia+MateriarizeCSS. It provides a glue logic to materializeCSS for <select> and others works with Aurelia.

https://github.com/jdanyow/aurelia-breeze-northwind

Hirano Satoshi

**Comment by pyarmak** [comment]
I decided to use materializeCSS simply because after speaking on gitter I learned from Rob Eisenberg that Aurelia will eventually have a front-end framework (something like aurelia-interface which is currently on github). Thus I felt that simply using CSS instead of another framework like polymer would be ok for the development state Aurelia is currently in (i.e. not production ready).

**Comment by HIRANO-Satoshi** [comment]
Thank you for reply.

MaterializeCSS is good choice since it seems nearly completed.

Aurelia-Interface seems quite incomplete and stops for long time.

I'm trying Polymer with Aurelia because Web components will become very popular maybe.
